### ISSUE TITLE
running the tool with no arguments results in error

### ISSUE THREAD

**Issue by johnathanvidu** [johnathanvidu/spdyn-update#1]
`Traceback (most recent call last):
  File "/home/johnathan/git/spdyn-update/run.py", line 7, in <module>
    spdyn.main()
  File "/home/johnathan/git/spdyn-update/spdyn_update/main.py", line 52, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'`

**Comment by johnathanvidu** [comment]
should display help in this case, or invoke some sort of default behavior
